name 'ivanlei-puppetdb'
version '1.6.0'
source 'git://github.com/ivanlei/puppetlabs-puppetdb.git'
author 'Puppet Labs'
description 'PuppetDB resource types'
summary 'PuppetDB resource types'
license 'ASL 2.0'
project_page 'https://github.com/ivanlei/puppetlabs-puppetdb'

dependency 'puppetlabs/inifile', '>= 0.10.3'
dependency 'puppetlabs/postgresql', '2.x'
dependency 'puppetlabs/firewall', '>= 0.0.4'
dependency 'puppetlabs/stdlib', '>= 2.2.0'
